version: '3'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # PostgreSQL Service
  db:
    image: postgres:12
    container_name: postgres_container
    environment:
      POSTGRES_DB: cares_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dion
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # ... (you can add other services like nginx, redis, etc.)

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
