version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: cares-web
        container_name: cares-web
        restart: always
        environment:
            - TZ=Asia/Jakarta
        ports:
            - 44070:80
            - 44071:443
        volumes:
            - .:/var/www/html
            - ./log/cron:/var/log/cron
